services:
  controller:
    build:
      context: .
      dockerfile: controller.dockerfile
    container_name: controller
    env_file: "common.env"
    command: ["bash", "controller_setup.sh"]
    hostname: controller
    stdin_open: true
    tty: true
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    # volumes:
        # - '/lib/modules/6.1.21.2-microsoft-standard-WSL2+:/lib/modules/6.1.21.2-microsoft-standard-WSL2+'
        # - '/sys/fs/cgroup:/sys/fs/cgroup'
    ports:
      - "80:80"
      - "6080:6080"
    networks:
      external:
        ipv4_address: 10.100.0.11
    extra_hosts:
      - "compute1.mgmt:10.100.0.31"
      - "network.mgmt:10.100.0.15"
      - "block1.mgmt:10.100.0.41"
      - "database:10.100.0.5"
      - "nfs_server:10.100.0.6"
      - "memcached_server:10.100.0.7"
    
  network:
    build:
      context: .
      dockerfile: network.dockerfile
    depends_on:
      - controller
    env_file: "common.env"
    command: ["tini", "/root/network_setup.sh"]
    stdin_open: true
    tty: true
    privileged: true
    container_name: network
    hostname: network
    cap_add:
      - NET_ADMIN
      - NET_RAW
    # volumes:
        # - '/lib/modules/6.1.21.2-microsoft-standard-WSL2+:/lib/modules/6.1.21.2-microsoft-standard-WSL2+'
        # - '/sys/fs/cgroup:/sys/fs/cgroup'
    networks:
      external:
        ipv4_address: 10.100.0.15
    extra_hosts:
      - "controller:10.100.0.11"
      - "compute1:10.0.0.31"
      - "block1:10.100.0.41"
      - "database:10.100.0.5"
      - "nfs_server:10.100.0.6"
      - "memcached_server:10.100.0.7"

  compute1:
    build:
      context: .
      dockerfile: compute1.dockerfile
    depends_on:
      - controller
    env_file: "common.env"
    command: ["tini", "/root/compute1_setup.sh"]
    stdin_open: true
    tty: true
    privileged: true
    container_name: compute1
    hostname: compute1
    cap_add:
      - NET_ADMIN
      - NET_RAW
    # volumes:
        # - '/lib/modules/6.1.21.2-microsoft-standard-WSL2+:/lib/modules/6.1.21.2-microsoft-standard-WSL2+'
        # - '/sys/fs/cgroup:/sys/fs/cgroup'
    networks:
      external:
        ipv4_address: 10.100.0.31
    extra_hosts:
      - "controller:10.100.0.11"
      - "network:10.0.0.15"
      - "block1:10.100.0.41"
      - "database:10.100.0.5"
      - "nfs_server:10.100.0.6"
      - "memcached_server:10.100.0.7"

  database:
    build:
      context: .
      dockerfile: database.dockerfile
    stdin_open: true
    env_file: "common.env"
    tty: true
    privileged: true
    container_name: database
    hostname: database
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      external:
        ipv4_address: 10.100.0.5
    extra_hosts:
      - "controller:10.100.0.11"
      - "network:10.100.0.15"
      - "compute1:10.100.0.31"
      - "block1:10.100.0.41"
      - "nfs_server:10.100.0.6"
      - "memcached_server:10.100.0.7"

  nfs_server:
    image: erichough/nfs-server
    privileged: true
    volumes:
      - ~/nfs_root:/srv/nfs4:rw
      - ~/nfs_home:/srv/nfs4/home:rw
      - ./exports.txt:/etc/exports:ro
    networks:
      external:
        ipv4_address: 10.100.0.6

  memcached_server:
    image: memcached
    # command: ["sed", "-i", "\"s/^-l 127.0.0.1$/-l 10.100.0.7/g\"", "/etc/memcached.conf"]
    networks:
      external:
        ipv4_address: 10.100.0.7

  block1:
    build:
      context: .
      dockerfile: block1.dockerfile
    stdin_open: true
    tty: true
    env_file: "common.env"
    command: ["bash", "/root/block1_setup.sh"]
    privileged: true
    container_name: block1
    hostname: block1
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      external:
        ipv4_address: 10.100.0.41
    extra_hosts:
      - "controller:10.100.0.11"
      - "network:10.100.0.15"
      - "compute1:10.100.0.31"
      - "database:10.100.0.5"
      - "nfs_server:10.100.0.6"
      - "memcached_server:10.100.0.7"

networks:
  external:
    attachable: true
    internal: false
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: external
      com.docker.network.driver.mtu: 9000
    ipam:
      driver: default
      config:
        - subnet: 10.100.0.0/24
          gateway: 10.100.0.1

