services:
  controller:
    build:
      context: .
      dockerfile: controller.dockerfile
    container_name: controller
    command: ["bash", "controller_setup.sh"]
    hostname: controller
    stdin_open: true
    tty: true
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    # volumes:
        # - '/lib/modules/6.1.21.2-microsoft-standard-WSL2+:/lib/modules/6.1.21.2-microsoft-standard-WSL2+'
        # - '/sys/fs/cgroup:/sys/fs/cgroup'
    ports:
      - "80:80"
      - "6080:6080"
    networks:
      external:
        ipv4_address: 10.100.0.11
    extra_hosts:
      - "compute1:10.0.0.31"
      - "network:10.0.0.15"
    
  network:
    build:
      context: .
      dockerfile: network.dockerfile
    depends_on:
      - controller
    command: ["tini", "/root/network_setup.sh"]
    stdin_open: true
    tty: true
    privileged: true
    container_name: network
    hostname: network
    cap_add:
      - NET_ADMIN
      - NET_RAW
    # volumes:
        # - '/lib/modules/6.1.21.2-microsoft-standard-WSL2+:/lib/modules/6.1.21.2-microsoft-standard-WSL2+'
        # - '/sys/fs/cgroup:/sys/fs/cgroup'
    networks:
      external:
        ipv4_address: 10.100.0.15
    extra_hosts:
      - "controller:10.0.0.11"
      - "compute1:10.0.0.31"

  compute1:
    build:
      context: .
      dockerfile: compute1.dockerfile
    depends_on:
      - controller
    command: ["tini", "/root/compute1_setup.sh"]
    stdin_open: true
    tty: true
    privileged: true
    container_name: compute1
    hostname: compute1
    cap_add:
      - NET_ADMIN
      - NET_RAW
    # volumes:
        # - '/lib/modules/6.1.21.2-microsoft-standard-WSL2+:/lib/modules/6.1.21.2-microsoft-standard-WSL2+'
        # - '/sys/fs/cgroup:/sys/fs/cgroup'
    networks:
      external:
        ipv4_address: 10.100.0.31
    extra_hosts:
      - "controller:10.0.0.11"
      - "network:10.0.0.15"

networks:
  external:
    attachable: true
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: mgmt
      com.docker.network.driver.mtu: 9000
    ipam:
      driver: default
      config:
        - subnet: 10.100.0.0/24
          gateway: 10.100.0.1

