apiVersion: v1
kind: Service
metadata:
  name: block1
spec:
  selector:
    app: block1
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: controller-wakeup
      protocol: TCP
      port: 8000
      targetPort: 8000