apiVersion: apps/v1
kind: Deployment
metadata:
  name: os-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: os-controller
  template:
    metadata:
      labels:
        app: os-controller
    spec:
      containers:
      - name: os-controller
        image: controller-image:latest
        imagePullPolicy: Never
        command: ["tini", "--", "/root/controller_setup.sh"]
        envFrom:
        - configMapRef:
            name: common-env
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 6080
          hostPort: 6080
        tty: true
        stdin: true