apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: database-image:latest
        imagePullPolicy: Never
        command: ["tini", "--", "/root/database_setup.sh"]
        securityContext:
          capabilities:
            add: ["NET_ADMIN", "NET_RAW"]
          privileged: true
        envFrom:
        - configMapRef:
            name: common-env
        tty: true
        stdin: true
