apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  selector:
    app: database
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
    - name: port-38313
      protocol: TCP
      port: 38313
      targetPort: 38313
    - name: udp-local
      protocol: UDP
      port: 56993
      targetPort: 56993
