apiVersion: v1
kind: Service
metadata:
  name: memcached-server
spec:
  selector:
    app: memcached-server
  ports:
    - name: memcached
      protocol: TCP
      port: 11211
      targetPort: 11211