apiVersion: v1
kind: Service
metadata:
  name: network
spec:
  selector:
    app: network
  ports:
    - name: dns-tcp
      protocol: TCP
      port: 53
      targetPort: 53
    - name: dns-tcp-local
      protocol: TCP
      port: 45283
      targetPort: 45283
    - name: ovsdb
      protocol: TCP
      port: 6640
      targetPort: 6640
    - name: ofc
      protocol: TCP
      port: 6633
      targetPort: 6633
    - name: dns-udb
      protocol: UDP
      port: 53
      targetPort: 53
    - name: dns-udb-local
      protocol: UDP
      port: 46915
      targetPort: 46915
    - name: dhcp
      protocol: UDP
      port: 67
      targetPort: 67
