apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-server
  template:
    metadata:
      labels:
        app: nfs-server
    spec:
      containers:
      - name: nfs-server
        image: erichough/nfs-server:latest
        env:
        - name: NFS_EXPORT_0
          value: "/srv/nfs4       *(rw,sync,fsid=0,crossmnt,no_subtree_check,no_root_squash)"
        - name: NFS_EXPORT_1
          value: "/srv/nfs4/home  *(rw,sync,no_subtree_check,no_root_squash)"
        securityContext:
          privileged: true
        volumeMounts:
        - name: nfs-root
          mountPath: /srv/nfs4
        - name: nfs-home
          mountPath: /srv/nfs4/home
        tty: true
        stdin: true
      volumes:
      - name: nfs-root
        emptyDir:
          sizeLimit: 500Mi
      - name: nfs-home
        emptyDir:
          sizeLimit: 10Gi
