apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-server
  template:
    metadata:
      labels:
        app: rabbitmq-server
    spec:
      containers:
      - name: rabbitmq-server
        image: rabbitmq-server-image:latest
        imagePullPolicy: Never
        tty: true
        stdin: true